# Generated by Django 5.1.5 on 2025-02-10 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='course_year_section',
            field=models.CharField(default='default_course_year_section', max_length=100),
        ),
    ]
